app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/**
 * Rotas de autenticação
 */
Route::get('painel/logout',  array('as' => 'painel.logout',      'uses' => 'App\Controllers\Painel\AuthController@getLogout'));
Route::get('painel/login',   array('as' => 'painel.login',       'uses' => 'App\Controllers\Painel\AuthController@getLogin'));
Route::post('painel/login',  array('as' => 'painel.login.post',  'uses' => 'App\Controllers\Painel\AuthController@postLogin'));
Route::resource('groups', 'App\Controllers\Painel\GroupController');

/**
 * Rotas do painel
 */
Route::group(array('prefix' => 'painel', 'before' => 'auth.admin'), function() {
    Route::any('/', 'App\Controllers\Painel\PaginasController@index');
    Route::resource('paginas', 'App\Controllers\Painel\PaginasController');
    Route::resource('colaboradores', 'App\Controllers\Painel\ColaboradorsController');
    Route::resource('atuacoes', 'App\Controllers\Painel\AtuacoesController');
    Route::resource('categorias', 'App\Controllers\Painel\CategoriasController');
    Route::resource('produtos', 'App\Controllers\Painel\ProdutosController');
    Route::resource('aplicacoes', 'App\Controllers\Painel\FeaturesController');
    Route::resource('noticias', 'App\Controllers\Painel\NoticiasController');
    Route::resource('midias', 'App\Controllers\Painel\MidiasController');
    Route::resource('midiatipos', 'App\Controllers\Painel\MidiatiposController');
    Route::resource('locais', 'App\Controllers\Painel\LocalsController');
    Route::resource('especificas', 'App\Controllers\Painel\EspecificasController');
    Route::get('especificas/json/{geralId}', 'App\Controllers\Painel\EspecificasController@getEspecificas');
    Route::resource('arquivos', 'App\Controllers\Painel\ArquivosController');
    Route::resource('arquivosEn', 'App\Controllers\Painel\ArquivosEnController');
    Route::resource('socials', 'App\Controllers\Painel\SocialsController');
    Route::resource('users', 'App\Controllers\Painel\UsersController');
    Route::resource('popups', 'App\Controllers\Painel\PopupsController');
    Route::resource('popup', 'App\Controllers\Painel\PopupsController');

    //Ordenamento de ítens
    Route::post('ordenar', 'App\Controllers\Painel\OrdenadorController@ordenar');
});

/**
 * Rota da home
 */
Route::get('/', function(){
    $atuacoes = Atuacao::ordered()->get();

    $textoHome = Pagina::where('slug', 'home')->first();
    $textoHome = $textoHome->traduz('texto');

    $noticias = Noticia::published()->limit(3)->get();

    $idioma = \Config::get('app.locale');
    $getPopup = Popup::publicado()->periodoAtual()->idioma($idioma)->first();

    if($getPopup)
        $popup = $getPopup->toJson();
    else
        $popup = false;

    View::share('popup', $popup);

    return View::make('site.home.index', compact('atuacoes', 'textoHome', 'noticias', 'popup'));
});

/**
 * Rotas do front-end
 */
Route::get('empresa', 'App\Controllers\Site\PaginasController@empresa');
Route::get('solucoes', 'App\Controllers\Site\AtuacoesController@lista');
Route::get('solucoes/area/{solucaSlug}', 'App\Controllers\Site\AtuacoesController@area');
Route::get('solucoes/produto/{produtoSlug}', 'App\Controllers\Site\AtuacoesController@produto');
Route::get('parceiros', 'App\Controllers\Site\PaginasController@parceiros');
Route::get('noticias', 'App\Controllers\Site\NoticiasController@lista');
Route::get('noticias/detalhe/{noticiaSlug}', 'App\Controllers\Site\NoticiasController@detalhe');
Route::get('midia', 'App\Controllers\Site\MidiasController@lista');
Route::get('midia/lista/{midiaTipo}', 'App\Controllers\Site\MidiasController@lista');
Route::get('midia/video/{videoId}', 'App\Controllers\Site\MidiasController@video');
Route::get('suporte', function(){
    return View::make('site.suporte.index');
});
Route::get('contato', 'App\Controllers\Site\ContatoController@index');
Route::post('contato', 'App\Controllers\Site\ContatoController@sendMail');
Route::get('ativar', 'App\Controllers\Site\ContatoController@ativacao');
Route::post('ativar', 'App\Controllers\Site\ContatoController@enviarAtivacao');

Route::post('busca', function(){
    // solucoes/produto/slug
    // solucoes/area/slug
    $termo = Input::get('busca');
    $query = <<<QRY
(SELECT
produtos.titulo as 'titulo',
produtos.titulo_en as 'titulo_en',
CONCAT('solucoes/produto/', produtos.slug) as 'url',
produtos.descricao as 'olho',
produtos.descricao_en as 'olho_en'
FROM produtos WHERE produtos.titulo like '%{$termo}%' OR produtos.titulo_en like '%{$termo}%')
UNION
(SELECT
atuacaos.titulo as 'titulo',
atuacaos.titulo_en as 'titulo_en',
CONCAT('solucoes/area/', atuacaos.slug) as 'url',
atuacaos.descricao as 'olho',
atuacaos.descricao_en as 'olho_en'
FROM atuacaos WHERE atuacaos.titulo like '%{$termo}%' OR atuacaos.titulo_en like '%{$termo}%')
QRY;
    $resultados = \DB::select(\DB::raw($query));
    return View::make('site.busca')->with('resultados', $resultados)->with('termo', $termo);
});

/**
 * Composers
 */
View::composer('site.layout.default', 'App\Composers\ContactsComposer');
View::composer('site.layout.default', 'App\Composers\SocialsComposer');

/* LOCALIZAÇÃO */
Route::get('idioma/{sigla_idioma?}', function($sigla_idioma){
    if($sigla_idioma == 'pt-br' || $sigla_idioma == 'en')
        Session::put('locale', $sigla_idioma);

    //return Redirect::back();
    return Redirect::to('/');
});

app/controllers/painel/ArquivosController.php
<?php namespace App\Controllers\Painel;

use BaseController, Response, Arquivo, Input, Image;

class ArquivosController extends BaseController {

	/**
	 * Arquivo Repository
	 * 
	 * @var Arquivo
	 */
	protected $arquivo;

	public function __construct(Arquivo $arquivo)
	{
		$this->arquivo = $arquivo;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		if (!Input::hasFile('path'))
		{
			$response = array('error' => 'Você precisa adicionar um arquivo');			
		}
		elseif ($input['titulo'] == "")
		{
			$response = array('error' => 'Você precisa adicionar um título');
		}
		else
		{
			$response = 'teste';

			$arquivo = Input::file('path');
 			$arquivo->move(public_path().'/uploads/arquivos/', $arquivo->getClientOriginalName());
			$input['path'] = '/uploads/arquivos/'.$arquivo->getClientOriginalName();

			$arquivo = $this->arquivo->create($input);
			if( $arquivo )
				$response = array('error' => false, 'msg' => 'Arquivo adicionado com sucesso', 'arquivoId' => $arquivo->id);
			else
				$response = array('error' => 'Falha ao adicionar arquivo');
		}
		echo json_encode($response);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$arquivo = $this->arquivo->find($id);
		@unlink(public_path($arquivo->path));
		if ($arquivo->delete()) 
		{
			$response = array('error' => false, 'msg' => 'Arquivo apagado com sucesso');
		}
		else
		{
			$response = array('error' => true, 'msg' => 'Erro ao deletar arquivo');
		}
		echo json_encode($response);
	}

}

app/controllers/painel/ArquivosEnController.php
<?php namespace App\Controllers\Painel;

use BaseController, Response, ArquivoEn, Input, Image;

class ArquivosEnController extends BaseController {

	/**
	 * Arquivo Repository
	 *
	 * @var Arquivo
	 */
	protected $arquivo;

	public function __construct(ArquivoEn $arquivo)
	{
		$this->arquivo = $arquivo;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		if (!Input::hasFile('path-en'))
		{
			$response = array('error' => 'Você precisa adicionar um arquivo');
		}
		elseif ($input['titulo'] == "")
		{
			$response = array('error' => 'Você precisa adicionar um título');
		}
		else
		{
			$response = 'teste';

			$arquivo = Input::file('path-en');
 			$arquivo->move(public_path().'/uploads/arquivos/', $arquivo->getClientOriginalName());
			$input['path'] = '/uploads/arquivos/'.$arquivo->getClientOriginalName();

			$arquivo = $this->arquivo->create($input);
			if( $arquivo )
				$response = array('error' => false, 'msg' => 'Arquivo adicionado com sucesso', 'arquivoId' => $arquivo->id);
			else
				$response = array('error' => 'Falha ao adicionar arquivo');
		}
		echo json_encode($response);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$arquivo = $this->arquivo->find($id);
		@unlink(public_path($arquivo->path));
		if ($arquivo->delete())
		{
			$response = array('error' => false, 'msg' => 'Arquivo apagado com sucesso');
		}
		else
		{
			$response = array('error' => true, 'msg' => 'Erro ao deletar arquivo');
		}
		echo json_encode($response);
	}

}

app/controllers/painel/AtuacoesController.php
<?php namespace App\Controllers\Painel;

/**
 * AtuacoesController.php
 *
 * AtuacoesController
 *
 * Add Seo features into CodeIgniter projects.
 *
 * @package     Package
 * @category    Category
 * @framework   Framework
 * @author      Author
 * @link        http://trupe.net
 * @version     Version
 * @todo        Check image deletion when editing or deleting object
 */

use Auth, BaseController, Form, Input, Redirect, Sentry, View,
    Validator, Atuacao, Image, File, Parser, Templates, Str;

class AtuacoesController extends BaseController
{
    /**
     * Atuacao Repository
     *
     * @var Atuacao
     */
    protected $atuacao;

    public function __construct(Atuacao $atuacao)
    {
        $this->atuacao = $atuacao;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $atuacoes = $this->atuacao->orderBy('ordem', 'asc')->get();

        return View::make('painel.atuacoes.index', compact('atuacoes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('painel.atuacoes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = Input::all();
        $input['user_id'] = Sentry::getUser()->id;
        $validation = Validator::make($input, Atuacao::$rules);

        if ($validation->passes()) { {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'atuacoes');
            }
            $this->atuacao->create($input);

            return Redirect::route('painel.atuacoes.index');
        }

        return Redirect::route('painel.atuacoes.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function show($id)
    {
        $atuacao = $this->atuacao->findOrFail($id);

        return View::make('painel.atuacoes.show', compact('atuacao'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function edit($id)
    {
        $atuacao = $this->atuacao->find($id);

        if (is_null($atuacao)) {
            return Redirect::route('painel.atuacoes.index');
        }

        return View::make('painel.atuacoes.edit', compact('atuacao'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function update($id)
    {
        $input = array_except(Input::all(), array('_method', 'imagem'));
        $validation = Validator::make($input, Atuacao::$rules);

        if ($validation->passes()) {
            $atuacao = $this->atuacao->find($id);
            if (Input::hasFile('imagem')) {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'atuacoes');
                @unlink(public_path(substr($atuacao->imagem, 1)));
            }
            $atuacao->update($input);

            return Redirect::route('painel.atuacoes.show', $id);
        }

        return Redirect::route('painel.atuacoes.edit', $id)
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function destroy($id)
    {
        $atuacao = $this->atuacao->find($id);

        @unlink(public_path(substr($colaborador->imagem, 1)));
        @unlink(public_path(substr(str_replace('/230x170_crop', '/77x50_crop', $colaborador->imagem), 1)));
        @unlink(public_path(substr(str_replace('/230x170_crop', '', $colaborador->imagem), 1)));

        $atuacao->delete();

        return Redirect::route('painel.atuacoes.index');
    }

}

app/controllers/painel/AuthController.php
<?php namespace App\Controllers\Painel;

    use Auth, BaseController, Form, Input, Redirect, Sentry, View;

    class AuthController extends BaseController
    {
        public function getLogin()
        {
            return View::make('painel.auth.login');
        }

        public function postLogin()
        {
            $credentials = array(
                'username'    => Input::get('username'),
                'password' => Input::get('password')
            );

            try {
                $user = Sentry::authenticate($credentials, false);

                if ($user) {
                    return Redirect::route('painel.paginas.index');
                }
            } catch (\Exception $e) {
                return Redirect::route('painel.login')->withErrors(array('login' => $e->getMessage()));
            }
        }

        public function getLogout()
        {
            Sentry::logout();

            return Redirect::route('painel.login');
        }

    }

app/controllers/painel/OrdenadorController.php
<?php namespace App\Controllers\Painel;

class OrdenadorController extends \BaseController
{
    public function ordenar()
    {
        $input = \Input::all();
        $model = $input['model'];
        $modelUcf = ucfirst($model);

        parse_str($input['itens'], $itens);

        $result = null;
        foreach ($itens[$model] as $key => $value) {
            $object = $modelUcf::find($value);
            $object->ordem = $key;
            $object->save();
        }

        return \Response::json(
                    array(
                        'error' 	=> 	false,
                        'message' 	=>	'Ítens ordenados com sucesso'
                    ), 200
                );

    }
}

app/views/painel/_layouts/default.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Arycom</title>

    <script src="{{ URL::asset('assets/js/vendor/modernizr-2.6.2.min.js' )}}"></script>

    <link href="{{ URL::asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/css/bootstrap-responsive.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/css/jasny-bootstrap.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/css/jasny-bootstrap-responsive.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/black-tie/jquery-ui.min.css">
    <style>
        body{
            padding-top: 60px;
        }
        .control-group{
            max-width:600px;
        }
    </style>
</head>
<body>
<div>
    @if (Sentry::check())
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="{{ URL::to('/') }}">Arycom</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="{{ Request::is('painel/paginas*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.paginas.index')}}">Paginas</a></li>
                        <li class="{{ Request::is('painel/colaboradores*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.colaboradores.index')}}">Colaboradores</a></li>
                        <li class="dropdown
                                {{ Request::is('painel/produtos*')
                                || Request::is('painel/atuacoes*')
                                || Request::is('painel/especificas*')
                                || Request::is('painel/categorias*') ? 'active' : '' }}">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Produtos <b class="caret"></b></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                <li><a href="{{ URL::route('painel.atuacoes.index')}}">Áreas Gerais de Atuação</a></li></li>
                                <li><a href="{{ URL::route('painel.especificas.index')}}">Áreas Específicas de Atuação</a></li></li>
                                <li><a href="{{ URL::route('painel.categorias.index')}}">Categorias</a></li>
                                <li><a href="{{ URL::route('painel.produtos.index')}}">Produtos</a></li>
                            </ul>
                        </li>
                        <li class="dropdown
                                {{ Request::is('painel/midias*') ? 'active' : '' }}">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Mídia <b class="caret"></b></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                <li><a href="{{ URL::route('painel.midias.index', array('tipo' => 1))}}">Fotos</a></li></li>
                                <li><a href="{{ URL::route('painel.midias.index', array('tipo' => 2))}}">Vídeos</a></li></li>
                            </ul>
                        </li>
                        <li class="{{ Request::is('painel/noticias*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.noticias.index')}}">Notícias</a></li>
                        <li class="{{ Request::is('painel/locais*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.locais.index')}}">Locais</a></li>
                        <li class="{{ Request::is('painel/socials*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.socials.index')}}">Redes Sociais</a></li>
                        <li class="{{ Request::is('painel/popup*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.popups.index')}}">Pop Ups</a></li>
                        <li class="{{ Request::is('painel/users*') ? 'active' : '' }}">
                            <a href="{{ URL::route('painel.users.index')}}">Usuários</a></li>
                    </ul>
                    <ul class="nav pull-right">
                        <li>
                            <a href="{{ URL::route('painel.logout') }}" class="pull-right">Logout</a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
    @endif

    <div class="container">
            @if (Session::has('message'))
                <div class="flash alert">
                    <p>{{ Session::get('message') }}</p>
                </div>
            @endif

            @yield('main')
        </div>
</div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ URL::asset('assets/js/vendor/jquery-1.9.1.min.js') }}"><\/script>')</script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="{{ URL::asset('assets/js/bootstrap.min.js' )}}"></script>
    <script src="{{ URL::asset('assets/js/jasny-bootstrap.min.js' )}}"></script>
    <script src="{{ URL::asset('assets/ckeditor/ckeditor.js' )}}"></script>
    <script src="{{ URL::asset('assets/js/plugins.js' )}}"></script>
    <script src="{{ URL::asset('assets/js/admin.js' )}}"></script>
    <script>
        function string_to_slug(str)
        {
          str = str.replace(/^\s+|\s+$/g, ''); // trim
          str = str.toLowerCase();

          // remove accents, swap ñ for n, etc
          var from = "ãàáäâèéëêìíïîõòóöôùúüûñç·/_,:;";
          var to   = "aaaaaeeeeiiiiooooouuuunc------";
          for (var i=0, l=from.length ; i<l ; i++) {
            str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
          }

          str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
            .replace(/\s+/g, '-') // collapse whitespace and replace by -
            .replace(/-+/g, '-'); // collapse dashes

          return str;
        }

        var title = $('#titulo'),
        slug = $('#slug');

        title.on('keyup', function() {
          var val = $(this).val();
          val = string_to_slug(val);
          slug.val(val);
        });

    </script>
</body>
</html>