app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/**
 * Rotas de autenticação
 */
Route::get('painel/logout',  array('as' => 'painel.logout',      'uses' => 'App\Controllers\Painel\AuthController@getLogout'));
Route::get('painel/login',   array('as' => 'painel.login',       'uses' => 'App\Controllers\Painel\AuthController@getLogin'));
Route::post('painel/login',  array('as' => 'painel.login.post',  'uses' => 'App\Controllers\Painel\AuthController@postLogin'));
Route::resource('groups', 'App\Controllers\Painel\GroupController');

/**
 * Rotas do painel
 */
Route::group(array('prefix' => 'painel', 'before' => 'auth.admin'), function() {
    Route::any('/', 'App\Controllers\Painel\PaginasController@index');
    Route::resource('paginas', 'App\Controllers\Painel\PaginasController');
    Route::resource('colaboradores', 'App\Controllers\Painel\ColaboradorsController');
    Route::resource('atuacoes', 'App\Controllers\Painel\AtuacoesController');
    Route::resource('categorias', 'App\Controllers\Painel\CategoriasController');
    Route::resource('produtos', 'App\Controllers\Painel\ProdutosController');
    Route::resource('aplicacoes', 'App\Controllers\Painel\FeaturesController');
    Route::resource('noticias', 'App\Controllers\Painel\NoticiasController');
    Route::resource('midias', 'App\Controllers\Painel\MidiasController');
    Route::resource('midiatipos', 'App\Controllers\Painel\MidiatiposController');
    Route::resource('locais', 'App\Controllers\Painel\LocalsController');
    Route::resource('especificas', 'App\Controllers\Painel\EspecificasController');
    Route::get('especificas/json/{geralId}', 'App\Controllers\Painel\EspecificasController@getEspecificas');
    Route::resource('arquivos', 'App\Controllers\Painel\ArquivosController');
    Route::resource('arquivosEn', 'App\Controllers\Painel\ArquivosEnController');
    Route::resource('socials', 'App\Controllers\Painel\SocialsController');
    Route::resource('users', 'App\Controllers\Painel\UsersController');
    Route::resource('popups', 'App\Controllers\Painel\PopupsController');
    Route::resource('popup', 'App\Controllers\Painel\PopupsController');

    //Ordenamento de ítens
    Route::post('ordenar', 'App\Controllers\Painel\OrdenadorController@ordenar');
});

/**
 * Rota da home
 */
Route::get('/', function(){
    $atuacoes = Atuacao::ordered()->get();

    $textoHome = Pagina::where('slug', 'home')->first();
    $textoHome = $textoHome->traduz('texto');

    $noticias = Noticia::published()->limit(3)->get();

    $idioma = \Config::get('app.locale');
    $getPopup = Popup::publicado()->periodoAtual()->idioma($idioma)->first();

    if($getPopup)
        $popup = $getPopup->toJson();
    else
        $popup = false;

    View::share('popup', $popup);

    return View::make('site.home.index', compact('atuacoes', 'textoHome', 'noticias', 'popup'));
});

/**
 * Rotas do front-end
 */
Route::get('empresa', 'App\Controllers\Site\PaginasController@empresa');
Route::get('solucoes', 'App\Controllers\Site\AtuacoesController@lista');
Route::get('solucoes/area/{solucaSlug}', 'App\Controllers\Site\AtuacoesController@area');
Route::get('solucoes/produto/{produtoSlug}', 'App\Controllers\Site\AtuacoesController@produto');
Route::get('parceiros', 'App\Controllers\Site\PaginasController@parceiros');
Route::get('noticias', 'App\Controllers\Site\NoticiasController@lista');
Route::get('noticias/detalhe/{noticiaSlug}', 'App\Controllers\Site\NoticiasController@detalhe');
Route::get('midia', 'App\Controllers\Site\MidiasController@lista');
Route::get('midia/lista/{midiaTipo}', 'App\Controllers\Site\MidiasController@lista');
Route::get('midia/video/{videoId}', 'App\Controllers\Site\MidiasController@video');
Route::get('suporte', function(){
    return View::make('site.suporte.index');
});
Route::get('contato', 'App\Controllers\Site\ContatoController@index');
Route::post('contato', 'App\Controllers\Site\ContatoController@sendMail');
Route::get('ativar', 'App\Controllers\Site\ContatoController@ativacao');
Route::post('ativar', 'App\Controllers\Site\ContatoController@enviarAtivacao');

Route::post('busca', function(){
    // solucoes/produto/slug
    // solucoes/area/slug
    $termo = Input::get('busca');
    $query = <<<QRY
(SELECT
produtos.titulo as 'titulo',
produtos.titulo_en as 'titulo_en',
CONCAT('solucoes/produto/', produtos.slug) as 'url',
produtos.descricao as 'olho',
produtos.descricao_en as 'olho_en'
FROM produtos WHERE produtos.titulo like '%{$termo}%' OR produtos.titulo_en like '%{$termo}%')
UNION
(SELECT
atuacaos.titulo as 'titulo',
atuacaos.titulo_en as 'titulo_en',
CONCAT('solucoes/area/', atuacaos.slug) as 'url',
atuacaos.descricao as 'olho',
atuacaos.descricao_en as 'olho_en'
FROM atuacaos WHERE atuacaos.titulo like '%{$termo}%' OR atuacaos.titulo_en like '%{$termo}%')
QRY;
    $resultados = \DB::select(\DB::raw($query));
    return View::make('site.busca')->with('resultados', $resultados)->with('termo', $termo);
});

/**
 * Composers
 */
View::composer('site.layout.default', 'App\Composers\ContactsComposer');
View::composer('site.layout.default', 'App\Composers\SocialsComposer');

/* LOCALIZAÇÃO */
Route::get('idioma/{sigla_idioma?}', function($sigla_idioma){
    if($sigla_idioma == 'pt-br' || $sigla_idioma == 'en')
        Session::put('locale', $sigla_idioma);

    //return Redirect::back();
    return Redirect::to('/');
});

app/controllers/painel/ArquivosController.php
<?php namespace App\Controllers\Painel;

use BaseController, Response, Arquivo, Input, Image;

class ArquivosController extends BaseController {

	/**
	 * Arquivo Repository
	 * 
	 * @var Arquivo
	 */
	protected $arquivo;

	public function __construct(Arquivo $arquivo)
	{
		$this->arquivo = $arquivo;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		if (!Input::hasFile('path'))
		{
			$response = array('error' => 'Você precisa adicionar um arquivo');			
		}
		elseif ($input['titulo'] == "")
		{
			$response = array('error' => 'Você precisa adicionar um título');
		}
		else
		{
			$response = 'teste';

			$arquivo = Input::file('path');
 			$arquivo->move(public_path().'/uploads/arquivos/', $arquivo->getClientOriginalName());
			$input['path'] = '/uploads/arquivos/'.$arquivo->getClientOriginalName();

			$arquivo = $this->arquivo->create($input);
			if( $arquivo )
				$response = array('error' => false, 'msg' => 'Arquivo adicionado com sucesso', 'arquivoId' => $arquivo->id);
			else
				$response = array('error' => 'Falha ao adicionar arquivo');
		}
		echo json_encode($response);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$arquivo = $this->arquivo->find($id);
		@unlink(public_path($arquivo->path));
		if ($arquivo->delete()) 
		{
			$response = array('error' => false, 'msg' => 'Arquivo apagado com sucesso');
		}
		else
		{
			$response = array('error' => true, 'msg' => 'Erro ao deletar arquivo');
		}
		echo json_encode($response);
	}

}

app/controllers/painel/ArquivosEnController.php
<?php namespace App\Controllers\Painel;

use BaseController, Response, ArquivoEn, Input, Image;

class ArquivosEnController extends BaseController {

	/**
	 * Arquivo Repository
	 *
	 * @var Arquivo
	 */
	protected $arquivo;

	public function __construct(ArquivoEn $arquivo)
	{
		$this->arquivo = $arquivo;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		if (!Input::hasFile('path-en'))
		{
			$response = array('error' => 'Você precisa adicionar um arquivo');
		}
		elseif ($input['titulo'] == "")
		{
			$response = array('error' => 'Você precisa adicionar um título');
		}
		else
		{
			$response = 'teste';

			$arquivo = Input::file('path-en');
 			$arquivo->move(public_path().'/uploads/arquivos/', $arquivo->getClientOriginalName());
			$input['path'] = '/uploads/arquivos/'.$arquivo->getClientOriginalName();

			$arquivo = $this->arquivo->create($input);
			if( $arquivo )
				$response = array('error' => false, 'msg' => 'Arquivo adicionado com sucesso', 'arquivoId' => $arquivo->id);
			else
				$response = array('error' => 'Falha ao adicionar arquivo');
		}
		echo json_encode($response);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$arquivo = $this->arquivo->find($id);
		@unlink(public_path($arquivo->path));
		if ($arquivo->delete())
		{
			$response = array('error' => false, 'msg' => 'Arquivo apagado com sucesso');
		}
		else
		{
			$response = array('error' => true, 'msg' => 'Erro ao deletar arquivo');
		}
		echo json_encode($response);
	}

}

app/controllers/painel/AtuacoesController.php
<?php namespace App\Controllers\Painel;

/**
 * AtuacoesController.php
 *
 * AtuacoesController
 *
 * Add Seo features into CodeIgniter projects.
 *
 * @package     Package
 * @category    Category
 * @framework   Framework
 * @author      Author
 * @link        http://trupe.net
 * @version     Version
 * @todo        Check image deletion when editing or deleting object
 */

use Auth, BaseController, Form, Input, Redirect, Sentry, View,
    Validator, Atuacao, Image, File, Parser, Templates, Str;

class AtuacoesController extends BaseController
{
    /**
     * Atuacao Repository
     *
     * @var Atuacao
     */
    protected $atuacao;

    public function __construct(Atuacao $atuacao)
    {
        $this->atuacao = $atuacao;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $atuacoes = $this->atuacao->orderBy('ordem', 'asc')->get();

        return View::make('painel.atuacoes.index', compact('atuacoes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('painel.atuacoes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = Input::all();
        $input['user_id'] = Sentry::getUser()->id;
        $validation = Validator::make($input, Atuacao::$rules);

        if ($validation->passes()) { {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'atuacoes');
            }
            $this->atuacao->create($input);

            return Redirect::route('painel.atuacoes.index');
        }

        return Redirect::route('painel.atuacoes.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function show($id)
    {
        $atuacao = $this->atuacao->findOrFail($id);

        return View::make('painel.atuacoes.show', compact('atuacao'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function edit($id)
    {
        $atuacao = $this->atuacao->find($id);

        if (is_null($atuacao)) {
            return Redirect::route('painel.atuacoes.index');
        }

        return View::make('painel.atuacoes.edit', compact('atuacao'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function update($id)
    {
        $input = array_except(Input::all(), array('_method', 'imagem'));
        $validation = Validator::make($input, Atuacao::$rules);

        if ($validation->passes()) {
            $atuacao = $this->atuacao->find($id);
            if (Input::hasFile('imagem')) {
                $input['imagem'] = Image::upload(Input::file('imagem'), 'atuacoes');
                @unlink(public_path(substr($atuacao->imagem, 1)));
            }
            $atuacao->update($input);

            return Redirect::route('painel.atuacoes.show', $id);
        }

        return Redirect::route('painel.atuacoes.edit', $id)
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function destroy($id)
    {
        $atuacao = $this->atuacao->find($id);

        @unlink(public_path(substr($colaborador->imagem, 1)));
        @unlink(public_path(substr(str_replace('/230x170_crop', '/77x50_crop', $colaborador->imagem), 1)));
        @unlink(public_path(substr(str_replace('/230x170_crop', '', $colaborador->imagem), 1)));

        $atuacao->delete();

        return Redirect::route('painel.atuacoes.index');
    }

}

app/controllers/painel/AuthController.php
<?php namespace App\Controllers\Painel;

    use Auth, BaseController, Form, Input, Redirect, Sentry, View;

    class AuthController extends BaseController
    {
        public function getLogin()
        {
            return View::make('painel.auth.login');
        }

        public function postLogin()
        {
            $credentials = array(
                'username'    => Input::get('username'),
                'password' => Input::get('password')
            );

            try {
                $user = Sentry::authenticate($credentials, false);

                if ($user) {
                    return Redirect::route('painel.paginas.index');
                }
            } catch (\Exception $e) {
                return Redirect::route('painel.login')->withErrors(array('login' => $e->getMessage()));
            }
        }

        public function getLogout()
        {
            Sentry::logout();

            return Redirect::route('painel.login');
        }

    }

app/controllers/painel/OrdenadorController.php
<?php namespace App\Controllers\Painel;

class OrdenadorController extends \BaseController
{
    public function ordenar()
    {
        $input = \Input::all();
        $model = $input['model'];
        $modelUcf = ucfirst($model);

        parse_str($input['itens'], $itens);

        $result = null;
        foreach ($itens[$model] as $key => $value) {
            $object = $modelUcf::find($value);
            $object->ordem = $key;
            $object->save();
        }

        return \Response::json(
                    array(
                        'error' 	=> 	false,
                        'message' 	=>	'Ítens ordenados com sucesso'
                    ), 200
                );

    }
}

app/views/painel/locais/edit.blade.php
@extends('painel._layouts.default')

@section('main')

<h1>Editar Local</h1>
{{ Form::model($local, array('files' => true, 'method' => 'PATCH', 'route' => array('painel.locais.update', $local->id))) }}
    <div class="control-group {{ $errors->first('titulo') ? 'error' : '' }}">
        {{ Form::label('titulo', 'Titulo:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('titulo', NULL, array('class' => 'span4')) }}
        </div>
        <h5>{{ $errors->first('titulo') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('titulo_en') ? 'error' : '' }}">
        {{ Form::label('titulo_en', 'Titulo (inglês):', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('titulo_en', NULL, array('class' => 'span4')) }}
        </div>
        <h5>{{ $errors->first('titulo_en') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('endereco') ? 'error' : '' }}">
        {{ Form::label('endereco', 'Endereço:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::textarea('endereco', NULL, array('class' => 'span4 ckeditor')) }}
        </div>
        <h5>{{ $errors->first('endereco') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('numero') ? 'error' : '' }}">
        {{ Form::label('numero', 'Número:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('numero', NULL, array('class' => 'input-small')) }}
        </div>
        <h5>{{ $errors->first('numero') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('titulo') ? 'error' : '' }}">
        {{ Form::label('complemento', 'Complemento:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('complemento') }}
        </div>
        <h5>{{ $errors->first('complemento') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('bairro') ? 'error' : '' }}">
        {{ Form::label('bairro', 'Bairro:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('bairro') }}
        </div>
        <h5>{{ $errors->first('bairro') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('cidade') ? 'error' : '' }}">
        {{ Form::label('cidade', 'Cidade:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('cidade') }}
        </div>
        <h5>{{ $errors->first('cidade') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('cep') ? 'error' : '' }}">
        {{ Form::label('cep', 'CEP:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('cep') }}
        </div>
        <h5>{{ $errors->first('cep') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('uf') ? 'error' : '' }}">
        {{ Form::label('uf', 'UF:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('uf', null, array('class' => 'input-small ')) }}
        </div>
        <h5>{{ $errors->first('uf') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('link_mapa') ? 'error' : '' }}">
        {{ Form::label('link_mapa', 'Código para mapa:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::textarea('link_mapa', null, array('class' => 'span4', 'rows' => '3')) }}
        </div>
        <h5>{{ $errors->first('link_mapa') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('ddd1') ? 'error' : '' }}">
        {{ Form::label('ddd1', 'DDD 1:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('ddd1', null, array('class' => 'input-small')) }}
        </div>
        <h5>{{ $errors->first('ddd1') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('telefone1') ? 'error' : '' }}">
        {{ Form::label('telefone1', 'Telefone 1:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('telefone1') }}
        </div>
        <h5>{{ $errors->first('telefone1') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('ddd2') ? 'error' : '' }}">
        {{ Form::label('ddd2', 'DDD 2:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('ddd2', null, array('class' => 'input-small')) }}
        </div>
        <h5>{{ $errors->first('ddd2') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('telefone2') ? 'error' : '' }}">
        {{ Form::label('telefone2', 'Telefone 2:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('telefone2') }}
        </div>
        <h5>{{ $errors->first('telefone2') }}<h5>
    </div>
    <div class="control-group {{ $errors->first('email') ? 'error' : '' }}">
        {{ Form::label('email', 'Email:', array('class' => 'control-label')) }}
        <div class="controls">
            {{ Form::text('email') }}
        </div>
        <h5>{{ $errors->first('email') }}<h5>
    </div>
    <div class="control-group">
        {{ Form::label('imagem', 'Imagem') }}

        <div class="fileupload fileupload-new" data-provides="fileupload">
            <div class="fileupload-preview thumbnail" style="width: 200px; height: 150px;">
                <img src="{{ URL::asset($local->imagem) }}">
            </div>
            <div>
                <span class="btn btn-file"><span class="fileupload-new">Selecionar imagem</span><span class="fileupload-exists">Alterar</span>{{ Form::file('imagem') }}</span>
            </div>
        </div>
    </div>
    {{ Form::submit('Atualizar', array('class' => 'btn btn-info')) }}
    {{ link_to_route('painel.locais.show', 'Cancelar', $local->id, array('class' => 'btn')) }}
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

@stop

app/views/painel/locais/index.blade.php
@extends('painel._layouts.default')

@section('main')

<h1>Locais</h1>

<p>{{ link_to_route('painel.locais.create', 'Novo local', NULL,
    array('class' => 'btn btn-mini btn-info')) }}
    <a href="#" data-model="local" class="ordenar btn btn-mini btn-info">Ordenar ítens</a></p>

@if ($locals->count())
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Imagem</th>
                <th>Criado por</th>
                <th class="span1"><i class="iconic-cog"></i></th>
            </tr>
        </thead>

        <tbody>
            @foreach ($locals as $local)
                    <tr id="local_{{ $local->id }}">
                    <td>{{{ $local->titulo }}}</td>
                    <td><img src="{{ URL::asset($local->imagem) }}" alt="{{ $local->titulo }}"></td>
                    <td>{{{ Sentry::getUserProvider()->findById($local->user_id)->first_name }}}</td>
                    <td>{{ link_to_route('painel.locais.edit', 'Editar', array($local->id), array('class' => 'btn btn-info btn-mini')) }}</td>
                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('painel.locais.destroy', $local->id))) }}
                            {{ Form::submit('Apagar', array('class' => 'btn btn-danger btn-mini')) }}
                        {{ Form::close() }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@else
    Nenhum local cadastrado.
@endif

@stop

app/views/painel/locais/show.blade.php
@extends('painel._layouts.default')

@section('main')

<h1>Show Local</h1>

<p>{{ link_to_route('painel.locais.index', 'Listar locais', null, array('class' => 'btn btn-info btn-mini')) }}</p>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th>Titulo</th>
			<th>Imagem</th>
			<th>Criado por</th>
			<th class="span1"><i class="iconic-cog"></i></th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $local->titulo }}}</td>
			<td><img src="{{ URL::asset($local->imagem) }}" alt="{{ $local->titulo }}"></td>
			<td>{{{ Sentry::getUserProvider()->findById($local->user_id)->first_name }}}</td>
            <td>{{ link_to_route('painel.locais.edit', 'Editar', array($local->id), array('class' => 'btn btn-info btn-mini')) }}</td>
            <td>
                {{ Form::open(array('method' => 'DELETE', 'route' => array('painel.locais.destroy', $local->id))) }}
                    {{ Form::submit('Apagar', array('class' => 'btn btn-danger btn-mini')) }}
                {{ Form::close() }}
            </td>
		</tr>
	</tbody>
</table>

@stop